export const glossary: Record<string, string> = {
  "APR": "Annual Percentage Rate — the yearly cost of borrowing, expressed as a percentage. A 22% APR means you pay $22 per year for every $100 owed.",
  "HYSA": "High-Yield Savings Account — a savings account paying significantly more interest than a standard account (often 4–5% APY vs. 0.01%).",
  "401(k)": "An employer-sponsored retirement savings plan. Contributions grow tax-advantaged until withdrawal in retirement.",
  "IRS": "Internal Revenue Service — the U.S. federal agency responsible for collecting taxes and administering tax law.",
  "index fund": "A fund that tracks a market index like the S&P 500. Low cost, broad diversification, and historically strong long-term returns.",
  "index funds": "Funds that track a market index like the S&P 500. Low cost, broad diversification, and historically strong long-term returns.",
  "emergency fund": "A cash reserve covering 3–6 months of essential expenses, kept liquid for unexpected costs like job loss or medical bills.",
  "compound interest": "Interest earned on both your principal and previously accumulated interest. Over time, it causes savings to grow exponentially.",
  "compounding": "The process of earning returns on both your principal and previously earned returns. The longer money compounds, the more powerful the effect.",
  "minimum payment": "The smallest amount you can pay on a credit card bill without penalty. Paying only the minimum leaves most of the balance to accumulate interest.",
  "net worth": "Total assets (what you own) minus total liabilities (what you owe). The most comprehensive snapshot of your financial position.",
  "opportunity cost": "The value of the next-best alternative you give up when making a choice. Spending $2,400 on a vacation has an opportunity cost of what that money could have earned or saved.",
  "lifestyle inflation": "The tendency to increase spending as income rises, often leaving savings rate unchanged despite earning more.",
  "tax-advantaged": "An account or investment with special tax benefits — either tax-deferred growth (traditional 401k, IRA) or tax-free growth (Roth).",
  "brokerage account": "A taxable investment account where you can buy and sell stocks, ETFs, and other securities. No contribution limits, but gains are taxed.",
  "credit card": "A revolving line of credit. Paid in full each month it costs nothing; carried as a balance it becomes one of the most expensive forms of debt.",
  "credit score": "A 300–850 number that measures creditworthiness. Affects loan rates, rental applications, and sometimes employment. Payment history is the biggest factor.",
  "interest rate": "The cost of borrowing, or the return on lending/saving, expressed as a percentage per year.",
  "principal": "The original amount borrowed or invested, before interest is added.",
  "tax refund": "Money returned to you by the IRS when you've overpaid taxes throughout the year. It's not a bonus — it's your own money returned without interest.",
  "debt avalanche": "A repayment strategy targeting the highest-interest debt first, minimizing total interest paid over time.",
  "debt snowball": "A repayment strategy targeting the smallest balance first, building psychological momentum regardless of interest rates.",
  "APY": "Annual Percentage Yield — the real rate of return on savings, accounting for compounding. Higher APY means your money grows faster.",
  "IRA": "Individual Retirement Account — a personal retirement savings account with tax advantages. Traditional IRAs offer tax-deferred growth; Roth IRAs offer tax-free growth.",
  "amortization": "The process of paying off debt through regular payments over time, with each payment covering both interest and a portion of the principal.",
  "liquidity": "How quickly and easily an asset can be converted to cash without losing value. A savings account is highly liquid; a house is not.",
};

export const glossaryTerms = Object.keys(glossary).sort((a, b) => b.length - a.length);
